name: CI

on:
  push:
    branches:
      - master
      - 'v*' # older version branches
    tags:
      - '*'

  pull_request: {}
  schedule:
  - cron:  '0 6 * * 0' # weekly, on sundays

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: install dependencies
      run: yarn install --frozen-lockfile --ignore-engines
    - name: lint
      run: yarn lint:js

  node-tests:
    name: "Node: Node ${{ matrix.node }} - ${{ matrix.os }}"
    runs-on: "${{matrix.os}}-latest"

    strategy:
      matrix:
        os: ['ubuntu', 'windows', 'macOS']
        node: ['14', '16', '18']

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install dependencies
      run: yarn install --frozen-lockfile --ignore-engines
    - name: test
      run: yarn test:node

  acceptance-tests:
    name: "Acceptance: Node ${{ matrix.node }} - ${{ matrix.os }}"
    runs-on: "${{matrix.os}}-latest"

    strategy:
      matrix:
        os: ['ubuntu', 'windows']
        node: ['14', '16', '18']

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install dependencies
      run: yarn install --frozen-lockfile --ignore-engines
    - name: test
      run: yarn test:ember

  floating-test:
    name: Floating dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: install dependencies
      run: yarn install --no-lockfile --ignore-engines
    - name: test
      run: yarn test

